// ********RoostGPT********
/*
Application Test generated by RoostGPT for test Application-Test-Golang using AI Type Open AI and AI Model gpt-4o


*/

// ********RoostGPT********
    func (app *application) all(w http.ResponseWriter, r *http.Request) {
        // Get all bookings stored
        bookings, err := app.bookings.All()
        if err != nil {
            app.serverError(w, err)
        }

        // Convert booking list into json encoding
        b, err := json.Marshal(bookings)
        if err != nil {
            app.serverError(w, err)
        }

        app.infoLog.Println("Bookings have been listed")

        // Send response back
        w.Header().Set("Content-Type", "application/json")
        w.WriteHeader(http.StatusOK)
        w.Write(b)
    }
    
